version : "3.8"

services:
  app:
    container_name: main_app
    build: .
    depends_on:
      - db

  db: 
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    env_file: .env
    
